### ISSUE TITLE
Max-height in title block image?

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#103]
I observed this in here `/2018/03/13/die-neuen-stadtkinder`

<img width="592" alt="screen shot 2018-05-04 at 11 29 18 am" src="https://user-images.githubusercontent.com/5600341/39633481-81612dfa-4f8e-11e8-8bce-b9855326c318.png">

@tpreusse do you think we should define a max-height for it?

Also in: `/2018/03/19/das-system-vincenz`

**Comment by tpreusse** [comment]
👍 a max height of 2/3 of the page should be adequate (with proportional down sizing)

**Comment by diegomura** [comment]
<img width="671" alt="screen shot 2018-05-12 at 9 06 09 pm" src="https://user-images.githubusercontent.com/5600341/39962554-522ec204-5628-11e8-906f-16bebc52c6c2.png">
<img width="671" alt="screen shot 2018-05-12 at 9 05 04 pm" src="https://user-images.githubusercontent.com/5600341/39962555-52560562-5628-11e8-8412-8deda9e7b12d.png">

Fixed in next react-pdf version. I was not fully supporting max|min height|width layout, so I had to change some things. I'm very happy with the final result.

Btw, @tpreusse as you can see in one of the images above, the figure legend fits the left side of the center column. That's because the figure width is still the whole column, but the image is being scaled because of #97. Not sure if it's the optimal look and feel, but we can eventually tweak this.

**Comment by diegomura** [comment]
Result when using `Center` instead of max-height on portrait cover images:

<img width="809" alt="screen shot 2018-05-16 at 11 05 11 am" src="https://user-images.githubusercontent.com/5600341/40121987-341fc960-58f9-11e8-940a-3f4baaf82852.png">
<img width="807" alt="screen shot 2018-05-16 at 11 05 18 am" src="https://user-images.githubusercontent.com/5600341/40121988-34449a60-58f9-11e8-8c36-d858d6b695a9.png">
