### ISSUE TITLE
Incorrect Image Sizes

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#106]
https://cdn.republik.space/pdf/2018/04/26/empoerung-dementi-und-ein-ruecktritt.pdf

<img width="839" alt="screen shot 2018-05-07 at 23 00 51" src="https://user-images.githubusercontent.com/410211/39724956-86fff4b2-524a-11e8-9cb0-50dc5349b5a5.png">

Seem to be broken since this:
https://github.com/diegomura/react-pdf/commit/a97e925604c6b659ab4e3688ef1223eac3a750d7#diff-40009642bf0fdd4bfadc278a03f2a6f7L84

Some how the image bounding box and element bounding box are not in sync—images are not downsized to the element bounding box.

**Comment by diegomura** [comment]
omg. checking this asap

**Comment by diegomura** [comment]
Fixed here: https://github.com/diegomura/react-pdf/commit/58c134fa762d2f8a4c12f8a49e8ce3400f87c93f

**Comment by tpreusse** [comment]
Thank you! Deployed it.
