### ISSUE TITLE
WIP: Analyse Infobox Wrapping and Loosen Up

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#109]
https://cdn.republik.space/pdf/2018/05/07/snb-bilanz-teil-2.pdf

Mulit paragraph info boxes cause large holes:
<img width="867" alt="screen shot 2018-05-08 at 17 05 02" src="https://user-images.githubusercontent.com/410211/39765389-0dd0cdd0-52e2-11e8-95d9-38a5fd4826ee.png">

We should probably allow them to wrap. But let's look at it systematically and optimize with the whole picture in mind. Opening now to not forget.

**Comment by diegomura** [comment]
Yes. That's definitely because of the `wrap=false`.
I'm sure we can find a solution to it

**Comment by tpreusse** [comment]
Improved with https://github.com/orbiting/pdf/pull/123. Let's open a new issue if we find new, bad examples.
