### ISSUE TITLE
Missing graphics

### ISSUE THREAD

**Issue by lwihler** [orbiting/pdf#134]
https://cdn.republik.space/pdf/2018/12/03/wo-die-waffen-sprechen.pdf

![image](https://user-images.githubusercontent.com/38752973/49389436-97a83000-f726-11e8-91c8-3d6ab5b9c8a7.png)

**Comment by tpreusse** [comment]
Temporary issue.

**Comment by patrickvenetz** [comment]
Closing issue as it appears to be resolved as of now.

<img width="479" alt="bildschirmfoto 2019-02-19 um 07 58 54" src="https://user-images.githubusercontent.com/331800/52995912-456cd600-341c-11e9-8d4f-218db1814b6f.png">
