### ISSUE TITLE
Teared Text

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#136]
`/2019/01/19/hoert-auf-mit-euren-geschichten.pdf` Page 4
<img width="813" alt="screenshot 2019-01-23 at 10 23 30" src="https://user-images.githubusercontent.com/410211/51596308-f30dc780-1ef8-11e9-9499-e9ec794c6036.png">

[Live PDF](https://cdn.republik.space/pdf/2019/01/19/hoert-auf-mit-euren-geschichten.pdf)

Similar issue in the past: https://github.com/orbiting/pdf/issues/132

**Comment by tpreusse** [comment]
Also odd line breaks on first page in the same PDF:
<img width="482" alt="screenshot 2019-01-29 at 10 48 32" src="https://user-images.githubusercontent.com/410211/51899505-70cb4a80-23b3-11e9-840d-c2c96431a8f3.png">

**Comment by tpreusse** [comment]
Another case:

`/2019/02/21/daten-von-allen-ehe-fuer-alle-und-einen-koennen-jetzt-alle-mal` Page 1
<img width="490" alt="screenshot 2019-02-21 at 11 54 46" src="https://user-images.githubusercontent.com/410211/53163954-80fbd180-35cf-11e9-8873-47484ef883bc.png">


[Live PDF](https://cdn.republik.space/pdf/2019/02/21/daten-von-allen-ehe-fuer-alle-und-einen-koennen-jetzt-alle-mal.pdf)

**Comment by diegomura** [comment]
With new textkit version:

- `/2019/02/21/daten-von-allen-ehe-fuer-alle-und-einen-koennen-jetzt-alle-mal`
<img width="560" alt="Screen Shot 2019-04-08 at 12 54 51 PM" src="https://user-images.githubusercontent.com/5600341/55738473-91d89900-59fd-11e9-92af-5d33a9af62fe.png">

- `/2019/01/19/hoert-auf-mit-euren-geschichten.pdf`
<img width="678" alt="Screen Shot 2019-04-08 at 12 58 16 PM" src="https://user-images.githubusercontent.com/5600341/55738893-65714c80-59fe-11e9-8d4d-f29e499799ad.png">
