### ISSUE TITLE
Update to new react-pdf version

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#137]
Hey @tpreusse and crew!

I'm opening this issue to track my research about the failures happening in Travis when the test script gets run on master. Hope you don't mind! It's on my interest that this project keeps updated, and I hope it's yours too 😄 

So far I could track the issue to the [last linebreaking](https://github.com/diegomura/react-pdf/commit/400b8b938f03989cefbc7a26bfa2d607e79fdf9e) changes that were introduced in `1.2.0` version.

When I run the script locally I don't observe any major performance downgrade, but the issue is that eventually the doc generation get's stuck almost everytime on `/2018/02/16/kosovo-unabhaengigkeit`. What's weird though is that if I individually render that doc in the browser (by just loading the url) the doc get's rendered. Any clues of what is going on? 

I'll continue to research though. But just wanted to keep you updated about it

**Comment by diegomura** [comment]
My bad. The script get's stuck in the document _after_ `/2018/02/16/kosovo-unabhaengigkeit`. At least almost every time. Running new tests to find which is the document causing troubles

**Comment by tpreusse** [comment]
Thanks for looking into this.

Maybe it's our asset server being really slow when rendering those charts?

I'll try testing locally later.

**Comment by tpreusse** [comment]
Nice, thank you for debugging and fixing this!

Re parallelism: Sounds interesting. Making it non-blocking is definitely good. Beyond that I'm quite happy with [regiment](https://github.com/orbiting/regiment) because it also gracefully replaces workers once they reach a certain memory footprint. Solving all leaks automatically :)

**Comment by tpreusse** [comment]
Done & bumped in https://github.com/orbiting/pdf/commit/4513db65539ecd759eb1e2dd11e61d6851ecbf4f

Thx @diegomura
