### ISSUE TITLE
Fail to return rendered PDF

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/pdf#139]
For some unknown reason [this document won't be returned as a render PDF](https://github.com/orbiting/pdf/blob/wont-render/fixtures/failing/wont-render.json) but seems to slip into a loop: node process continuously consumes CPU until process is stopped.

There is no error thrown.

A [previous version is rendered as expected](https://github.com/orbiting/pdf/blob/wont-render/fixtures/some-article.json).

**How to reproduce**
1. Checkout branch [`wont-render`](https://github.com/orbiting/pdf/tree/wont-render)
2. [Install dependencies, launch in dev mode](https://github.com/orbiting/pdf/tree/wont-render#render-mdast-as-pdf)
3. Open http://localhost:3007/fixtures/failing/wont-render

**Expected result**
Returns render PDF

**Actual result**
Won't return render PDF. Node process continuously consumes CPU.

**Hints**
* Document failed to render after a particular commit ([see not public repository](https://github.com/republik/article-das-reaktionaerste-land-der-welt/commit/e046a80072b2863a3abed6f52db9d72bcf8d6f10))
* Removing all soft hyphens `U+00AD` returned rendered PDF
* Document is render including [some soft hyphens before a particular commit](https://github.com/orbiting/pdf/blob/wont-render/fixtures/some-article.json)

**Comment by tpreusse** [comment]
Fixed with newer react-pdf: https://github.com/orbiting/pdf/commit/4513db65539ecd759eb1e2dd11e61d6851ecbf4f
