### ISSUE TITLE
EMBEDVIDEO Zone

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#66]
The zone `EMBEDVIDEO` is currently handled by the render as image fallback. And comes with a play button, tracking warning and the image even when `images=0`. We should implement the element natively. Here the specs:

- 3 states, [see web code](https://github.com/orbiting/styleguide/blob/831cf8b8415dab72b981f155a6455a711feaa60c/src/templates/Article/index.js#L767)
  - audio: `data.forceAudio && data.src`
    - render static centred alt text: `Audio` (we'll improve later)
    - [example](https://www.republik.ch/2018/01/29/geheimsache-doping-teil1)
  - our videos: `data.src`
    - render thumbnail with static legend `Video`, if images=0: only `Video` as centred alt text
    - [example](https://www.republik.ch/2018/04/21/kloten-switzerland)
  - vimeo / youtube embed: `!data.src`
    - render thumbnail with `data.title` as legend, if images=0: only `data.title` as centred alt text
    - [example](https://www.republik.ch/2018/01/23/bergs-nerds-1)

**Comment by diegomura** [comment]
**Without skipping images:**
<img width="808" alt="screen shot 2018-05-02 at 2 28 40 pm" src="https://user-images.githubusercontent.com/5600341/39539103-2b81d6ca-4e15-11e8-867c-e21e504fd2d0.png">

**Skipping images:**
<img width="821" alt="screen shot 2018-05-02 at 2 28 29 pm" src="https://user-images.githubusercontent.com/5600341/39539120-389b58ae-4e15-11e8-885f-3fa36ab0ca83.png">

**Comment by diegomura** [comment]
@tpreusse there you can see the three scenarios (ordered). 
Not sure if you would like to apply any other styles to the alt texts
