### ISSUE TITLE
Justification Engine: Single Line Paragraph getting stretched

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#67]
http://localhost:3007/2018/04/25/das-kartell-teil-2-der-whistleblower
```json
{
  "children": [
    {
      "type": "text",
      "value": "Doch sie entsendet ein Sonderkommando.  "
    }
  ],
  "type": "paragraph"
}
```
<img width="837" alt="screen shot 2018-04-25 at 15 45 29" src="https://user-images.githubusercontent.com/410211/39249793-bbeed21a-489f-11e8-8bd8-f5a5df44f159.png">

**Comment by diegomura** [comment]
Fixed
<img width="1029" alt="screen shot 2018-04-25 at 3 56 46 pm" src="https://user-images.githubusercontent.com/5600341/39266751-4868736c-48a1-11e8-8a48-460d5dcec183.png">
