### ISSUE TITLE
Gylphs incorrectly rendered

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#76]
http://localhost:3007/2018/01/19/usa-serie

Might be solved on #52

**Comment by diegomura** [comment]
Glyph boxes are not getting rendered anymore since we implemented defautl font fallback in #52 .
However, this is still being bad justified due to this odd glyphs:

<img width="294" alt="screen shot 2018-05-02 at 12 34 01 pm" src="https://user-images.githubusercontent.com/5600341/39533375-3f0db73c-4e05-11e8-95ba-461448cb6b83.png">

The line breaking algorithm is adding a new line between those two chars. Those are [line separator characters](https://www.fileformat.info/info/unicode/char/2028/index.htm).
@tpreusse I'm not sure which is the way to proceed here. what should we do if we find a char like this one?

**Comment by tpreusse** [comment]
Source: Probably pasting from word.

I'll strip it manually in this document.

Possible long term solution: Strip invisible characters (like `\u2028`) automatically or render in visibly (like browsers seem to do)

**Comment by tpreusse** [comment]
manual fix done. for the record:

before manual fix
<img width="506" alt="screen shot 2018-05-02 at 18 11 38" src="https://user-images.githubusercontent.com/410211/39535528-690816e8-4e34-11e8-98b0-446236e7cfd0.png">

after
<img width="490" alt="screen shot 2018-05-02 at 18 12 04" src="https://user-images.githubusercontent.com/410211/39535536-6f53817c-4e34-11e8-983e-5915d1591222.png">

the rendering of `\u2028` as brackets with the default font is most likely wrong

**Comment by diegomura** [comment]
In `/2018/02/12/sie-wir-und-unser-gemeinsames-unternehmen`:

<img width="938" alt="screen shot 2018-05-04 at 10 35 47 am" src="https://user-images.githubusercontent.com/5600341/39630849-fa94407a-4f86-11e8-9604-0d6add3d265c.png">

**Comment by diegomura** [comment]
@tpreusse  Standalone Textkit loads the OS Emoji font, and transforms it into images when layout, which looks a bit pixelated, but does the job. The bad part is that this font weights +130MB in MacOS, so we cannot ship it with our solution and use it as another fallback font

<img width="826" alt="screen shot 2018-05-07 at 12 36 43 pm" src="https://user-images.githubusercontent.com/5600341/39710500-5b694972-51f3-11e8-8fd2-2e8065f701b9.png">

**Comment by tpreusse** [comment]
re `default ignorable spec`:
Unsure what the best place would be to ignore those. Since some font could define them, right? I guess it should skip rendering the missing glyph symbol for the ignorable chars as late as possible—maybe in the pdf-renderer in `textkit`? And properly mark as missing in the `font-substitution-engine`?

**Comment by tpreusse** [comment]
re emoji:
I guess since it should stay runnable on the web gitmoji seems to be the best option. Only loading the actually used emoji. Just make sure document it and make the emoji host/base url configurable.

Eventually I could also see a `font-manager` comeback (e.g. via configurable font substitution engine) for server apps that want to use a emoji font. However loading a 130mb font into memory is also not super desirable on most servers and most server distros seem to not ship one by default.

I'd bet on the image solution.

**Comment by diegomura** [comment]
`re default ignorable spec`
But do we even want to support rendering these type of glyphs if the font supports it? Based on the unicode spec, these `should be ignored by default in rendering (unless
explicitly supported). They have no visible glyph or advance width in and of themselves`. If that's the case, doing this early in the process would be extremely simpler

IMO pdf-renderer should not have this logic. From my point of view, this module should only be responsible of rendering what's given to him, but not taking decision of whats get's renderer and what's not. 

`re emoji:`
I agree. The only caveat I'm worried about is that we would be repending on a third-party service to render documents (even if GH is reliable, it can fail or change), and you will need to be connected to the internet to render documents (which is probably the 99% of the cases, buy anyway)

**Comment by diegomura** [comment]
`re default ignorable spec`
> That would be in font-substitution-engine right?
Yes. I think it makes sense to do it here. I still don't see any scenario in which someone would like to render a LINE SEPARATOR (or similar ignorable char), but it's ok to have it. Not sure how much of logic I'll have to change in this end to support this

`re emoji`
I agree that has to be configurable. The solution still feels a bit odd. A a user, I would like to render emojis right away with no config, but I don't think this is an option right now

**Comment by diegomura** [comment]
## Updates

### Default ignorable chars
I fixed this on the textkit side. However, I have to admit that I'm not very happy with the solution. It just feels hacky. I still think we should tackle this sooner in the process. While working on this today (both tickets were harder than I thought) I realize we can tackle this even on the react-pdf side, and still being able to render ignorable glyphs if present in TTF font. Operating with textkit data structures is not easy in some situations, specially when removing glyphs from runs 

### Emoji
I'm very close on finishing this feature. For this, I had to fix textkit's `attachment` API, that was not that straightforward. #87 changes jsut made everything more complicated. I still have to: 

- [ ] Build the public API to register an emoji CDN URL (this should be splitted in different fields, such as the url itself, image format, etc)
- [ ] Add support to more than one attachment per run (currently textkit supports just one)
- [ ] Contemplate what happens when no URL is given (probably not render anything)

**Comment by tpreusse** [comment]
## Default ignorable chars

I think use the example of `\u00ad` (the soft hyphen, a default ignorable) to decide what to do. If you can stripe or suppress it early but still use it in line breaking to insert a hard hyphen if need, do it. If it causes trouble when you strip it early. Don't.

## Emoji

Good to hear. One more input: It should also be compatible with [`twemoji`](https://github.com/twitter/twemoji). Twitter is a more active emoji player than GitHub. Their emojis are available on maxcdn with their key code: [`2764`](https://twemoji.maxcdn.com/2/72x72/2764.png)

But also skin color support, via [HEX code point ranges](https://github.com/twitter/twemoji#utilities).

Example victory without skin color [`270c`](https://twemoji.maxcdn.com/2/72x72/270c.png) with skin color [`270c-1f3fc`](https://twemoji.maxcdn.com/2/72x72/270c-1f3fc.png)

They use [this regex](https://github.com/twitter/twemoji/blob/7c1d3e953dd5cfa021f58aefb450ec54120d4efa/twemoji.js#L236) and then the code point utils. Does GitHub handle modifiers like gender and skin color?

I feel bad that this is already getting complicated again. But I feel like if we're not doing modifiers we'll don't have true emoji support and run into missing/wrong glyph again.

> Contemplate what happens when no URL is given (probably not render anything)
Render the missing-glyph glyph or draw an small empty rect.

**Comment by diegomura** [comment]
There are some emoijs that twemoji's regex does not catch

<img width="1481" alt="screen shot 2018-05-08 at 12 37 57 pm" src="https://user-images.githubusercontent.com/5600341/39767256-ae02f934-52bc-11e8-8635-6b5543e1bdce.png">

**Comment by diegomura** [comment]
Yes. Otherwise, there is this handy lib, that even supports text emoji representation (if needed in the future: https://github.com/mathiasbynens/emoji-regex

The only issue I'm having right now is that I need a way of splitting strings on emojis, to create several runs (because we can only setup 1 attachment per run), and none of this regex throws the desire result.

**Comment by diegomura** [comment]
Not supported emojis (just for future reference):
 - Happy face
 - Sad face
 - Gear
 - Snowflake
 - Shamrock
