### ISSUE TITLE
Infinite Loop / Timeout

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#82]
`/2018/04/27/was-diese-woche-wichtig-war-17.pdf` (prd)

Can't figure out where it breaks. No error shown on the console.
It just crashes after a few minutes:
```
> Ready on port 3007
[nodemon] app crashed - waiting for file changes before starting...
```

Maybe timeout barriers could help narrow down where it is taking forever. 

Process Sample seems to point to Yoga but not sure:
<img width="1423" alt="screen shot 2018-04-29 at 14 36 50" src="https://user-images.githubusercontent.com/410211/39406772-4cead240-4bbc-11e8-9520-0b8db0294ae0.png">

**Comment by diegomura** [comment]
Fixed on: https://github.com/react-pdf/linebreaker/commit/fd2efda576c7533c55ace99c60d4c72caae3cd6c
Both cases worked fine for me locally. Waiting to promote this to prod to close this issue

**Comment by diegomura** [comment]
Working: https://pdf.republik.space/2018/04/27/was-diese-woche-wichtig-war-17.pdf ✅
