### ISSUE TITLE
Avoid Tiny Wrappings

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#85]
### Block Quote Example
`/2018/04/25/hausverbot-im-zueriwc.pdf?images=0` (prd)

<img width="818" alt="screen shot 2018-04-29 at 15 10 55" src="https://user-images.githubusercontent.com/410211/39406993-a45b8f8a-4bbf-11e8-98eb-2457acb67183.png">

_block quote should be able to wrap but in this case it should wrap before the block quote starts_

### Paragraph Example
`/2018/04/25/das-kartell-teil-2-der-whistleblower.pdf` (prd)

<img width="817" alt="screen shot 2018-04-29 at 15 14 35" src="https://user-images.githubusercontent.com/410211/39407029-263b2d58-4bc0-11e8-9847-bdc0321c06cd.png">

_single lines should not be alone, wrap before the whole p (only if the p can fit on one page without wrapping)_

Another example: `/2018/04/24/das-kartell-teil-1-der-aussteiger.pdf` (prd)

<img width="829" alt="screen shot 2018-04-29 at 15 17 43" src="https://user-images.githubusercontent.com/410211/39407060-967f0a44-4bc0-11e8-9e6f-9c07cf29f0a1.png">

_wrap before «Die Mutter[...]»_

**Comment by tpreusse** [comment]
Also read: https://en.wikipedia.org/wiki/Widows_and_orphans

**Comment by diegomura** [comment]
Fixed in https://github.com/diegomura/react-pdf/pull/226

**Comment by diegomura** [comment]
Refer to images in PR.

Original documents here:
[no-orphans-or-widows.pdf](https://github.com/orbiting/pdf/files/1972390/no-orphans-or-widows.pdf)
[original.pdf](https://github.com/orbiting/pdf/files/1972391/original.pdf)
