### ISSUE TITLE
linebreak settings / hyphenation penalty depending on text align value

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#89]
A low prio thing:
Would it be possible to raise the penalty of hyphens for not justified text? For justified text the current settings are perfect.

When `textAlign` is not `justify` the logic should be something like «only insert an hyphen when a word is longer than 50% of the line».

**Comment by diegomura** [comment]
Yes. I think we can manage to do something like this!

**Comment by diegomura** [comment]
Fixed here: https://github.com/react-pdf/linebreaker/commit/fdffeb779a25c4a80c6632255a45c7b7e04a5b8a
