### ISSUE TITLE
Perf improvement: Cache fonts 

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#93]
If we download fonts when project starts, we can get a performance improvement by preventing many network request to happen

**Comment by tpreusse** [comment]
a previously existing cache was removed here: https://github.com/orbiting/pdf/commit/8fad0541a6b736b2cfac80e486944889468405bb (maybe useful ref, not sure if it was implemented ideally)

**Comment by diegomura** [comment]
Thanks! Yes. I remember seeing it. Don’t remember why it was taken away

**Comment by diegomura** [comment]
You were right about this.
React-pdf already caches font in memory. So they are basically downloaded the first time, and then reused throughout all documents. Sorry for my bad memory! But the good news is that I found an improvement while researching this, which I'll commit to react-pdf and will be merged on next version.

<img width="1172" alt="screen shot 2018-05-03 at 5 12 46 pm" src="https://user-images.githubusercontent.com/5600341/39600609-9fe4571e-4ef5-11e8-877c-50f0936cb8e0.png">

_(you can see the start or end of the document rendering, and when a font is fetched. Here there are two consecutive document rendering)
