### ISSUE TITLE
Image Exceeding Page Height

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#97]
http://localhost:3007/2018/02/22/die-illegale-suche-nach-den-datenzwillingen.pdf (prd)

Contains a HTML element that is rendered as an image with the dimensions [665 × 1694](https://cdn.republik.space/render?width=665&height=1&id=cmVwbzpyZXB1Ymxpay9hcnRpY2xlLW5vYmlsbGFnLWdlZ25lci11bmQtaWhyLXZlcnJhdDoyZGY5NzIwMWEzZGYxNDAyMTNhMDQ5Y2E3YmI4NjAyNzgxYWFlYjA1&url=https%3A%2F%2Fwww.republik.ch%2F2018%2F02%2F22%2Fdie-illegale-suche-nach-den-datenzwillingen%3Fextract%3D1%3A40%26unpack%3D2) which exceed the space of one page and never finishes processing. Infinite loop in the wrap algo?

Ideally we could say a image may wrap with `<Image wrap />` and do so in `<RenderAsImage />`.

What already works: setting a `maxHeight`, e.g. 700. However the output image is squeezed:
<img width="408" alt="screen shot 2018-05-03 at 23 19 05" src="https://user-images.githubusercontent.com/410211/39603365-68af7e58-4f28-11e8-956a-264ba42e48fe.png">

ToDo, in a order that I'd guess is easiest:
- [ ] scale image proportionally when a max height and no width is set
- [ ] fix infinite loop and place element on a page alone anyhow
- ~wrap images if they do not fit on one page and do not have a max height~

**Comment by diegomura** [comment]
@tpreusse  By wrap images (3rd checkbox) you mean breaking the image in two so it can be rendered in two pages? 
I think the most easy way of fixing this is by just not allowing to any image to exceed the page height

**Comment by tpreusse** [comment]
> By wrap images (3rd checkbox) you mean breaking the image in two so it can be rendered in two pages?
Yeah. But probably not super useful anyhow. So lets not do it:

> I think the most easy way of fixing this is by just not allowing to any image to exceed the page height
Fine with me. Just make sure to scale down the image proportionally.

**Comment by diegomura** [comment]
This image shows how the image gets scaled proportionally inside his bounding box when excedes the page available space:

<img width="665" alt="screen shot 2018-05-04 at 3 31 56 pm" src="https://user-images.githubusercontent.com/5600341/39646534-200f18c2-4fb2-11e8-8390-74eef71a4b40.png">

Orange: Image margins
Blue: Image element bounding box
Red: Used image space (scaled proportionally)

**Comment by diegomura** [comment]
Fixed in react-pdf#0.7.7-21
